// Durchgespielte Beispielhände. Jede Hand läuft Straße für Straße; nach jeder Entscheidung
// geht es mit der richtigen Aktion weiter. Karten: Rang + Farbe (s=♠, h=♥, d=♦, c=♣).
// step.notes überschreibt die Anzeige einzelner Plätze (Standard: Du / Gegner / Gepasst).
window.EXAMPLES = [
  {
    id: "value",
    title: "Top Pair vom Button: Value holen",
    teaser: "Du eröffnest mit A♠K♦, triffst ein Ass und spielst die Hand für Value.",
    lesson: "Open-Raise, C-Bet auf trockenem Board, Value-Bets",
    players: 6, hero: "BTN", villain: "BB", heroCards: ["As", "Kd"],
    steps: [
      {
        street: "preflop", board: [], pot: 1.5,
        notes: { BB: "Noch dran", SB: "Noch dran" },
        log: ["UTG passt.", "HJ passt.", "CO passt."],
        hand: "A♠K♦: zwei hohe Karten, eine der stärksten Starthände.",
        prompt: "Alle haben bis zu dir gepasst. Im Pot liegen nur die Blinds (1,5bb). Was tust du?",
        options: ["Passen", "Mitgehen (Limpen, 1bb)", "Erhöhen auf 2,5bb"],
        answer: 2,
        why: "AKo gehört von jedem Platz in die Eröffnungs-Range. Am Button eröffnest du sogar etwa die Hälfte aller Hände. Limpen ist kein Teil einer GTO-Strategie: Mit einer Erhöhung gewinnst du oft sofort die Blinds und hast die Initiative.",
        next: "Der SB passt, der BB geht mit. Im Pot sind jetzt 5,5bb (deine 2,5 + 2,5 vom BB + 0,5 vom SB).",
      },
      {
        street: "flop", board: ["Ah", "7c", "2d"], pot: 5.5,
        log: ["Der Flop kommt: A♥ 7♣ 2♦.", "Der BB checkt."],
        hand: "Du hast ein Paar Asse mit König als Kicker: Top Pair mit dem bestmöglichen Kicker.",
        prompt: "Der BB checkt zu dir. Was tust du?",
        options: ["Checken", "Klein setzen: 1,8bb (ca. 1/3 Pot)", "Groß setzen: 5,5bb (Pot)"],
        answer: 1,
        why: "A-7-2 in drei Farben ist ein trockener Flop, der dir als Preflop-Raiser sehr gut liegt: Du hast viel mehr Asse und starke Hände in deiner Range als der BB (Range-Vorteil). Auf solchen Boards setzt man oft und klein. Schwächere Asse, Siebenen und kleine Paare des BB zahlen eine kleine Bet gern.",
        next: "Der BB geht mit. Pot: 5,5 + 1,8 + 1,8 = 9,1bb.",
      },
      {
        street: "turn", board: ["Ah", "7c", "2d", "5s"], pot: 9.1,
        log: ["Der Turn ist die 5♠.", "Der BB checkt."],
        hand: "Immer noch Top Pair mit bestem Kicker. Die 5♠ ändert kaum etwas.",
        prompt: "Der BB checkt wieder. Was tust du?",
        options: ["Checken", "Setzen: 6bb (ca. 2/3 Pot)", "All-in: 95,7bb"],
        answer: 1,
        why: "Deine Hand ist sehr wahrscheinlich vorne, und viele schlechtere Hände (A9, A8, 77-Paare, 7x) zahlen noch eine Bet. Das ist eine Value-Bet. All-in wäre zu groß: Dann gehen nur noch Hände mit, die dich schlagen.",
        next: "Der BB geht mit. Pot: 9,1 + 6 + 6 = 21,1bb.",
      },
      {
        street: "river", board: ["Ah", "7c", "2d", "5s", "Kc"], pot: 21.1,
        log: ["Der River ist der K♣.", "Der BB checkt."],
        hand: "Jetzt hast du Zwei Paare: Asse und Könige.",
        prompt: "Der BB checkt ein drittes Mal. Was tust du?",
        options: ["Checken (Showdown)", "Setzen: 16bb (ca. 3/4 Pot)", "Passen"],
        answer: 1,
        why: "Mit Zwei Paaren schlägst du fast alle Hände, die bis hierhin mitgegangen sind (z. B. AQ, AJ, A5). Wer checkt, verschenkt Geld, das schlechtere Hände noch bezahlt hätten. Passen geht hier übrigens gar nicht: Niemand hat gesetzt, also kannst du kostenlos checken.",
        next: "Der BB geht mit und zeigt A♣J♦. Du gewinnst einen Pot von 53,1bb.",
      },
    ],
  },
  {
    id: "draw",
    title: "Flush-Draw im Big Blind: Pot Odds rechnen",
    teaser: "Du verteidigst mit K♥T♥, floppst einen Flush-Draw und rechnest, ob sich Callen lohnt.",
    lesson: "Verteidigen im BB, Pot Odds, Outs, MDF",
    players: 6, hero: "BB", villain: "BTN", heroCards: ["Kh", "Th"],
    steps: [
      {
        street: "preflop", board: [], pot: 4,
        notes: { BTN: "Erhöht 2,5bb" },
        log: ["UTG, HJ und CO passen.", "Der Button erhöht auf 2,5bb.", "Der SB passt."],
        hand: "K♥T♥: König-Zehn suited, eine ordentliche, gut spielbare Hand.",
        prompt: "Der Button hat erhöht. Du sitzt im Big Blind und hast schon 1bb im Pot. Was tust du?",
        options: ["Passen", "Mitgehen (1,5bb mehr)", "3-Bet auf 11bb"],
        answer: 1,
        ok: [2],
        why: "Der Button eröffnet eine sehr breite Range, und du musst nur noch 1,5bb zahlen, um einen Pot von 5,5bb zu spielen. Das ist ein guter Preis. KTs ist zu gut zum Passen, aber eine 3-Bet bringt hier vor allem schlechtere Hände zum Passen. Mitgehen ist der Standard. (Eine 3-Bet spielen Solver damit manchmal auch.)",
        next: "Pot: 5,5bb. Du bist nach dem Flop ohne Position: Du musst auf jeder Straße zuerst handeln.",
      },
      {
        street: "flop", board: ["Jh", "6h", "2c"], pot: 5.5,
        log: ["Der Flop kommt: J♥ 6♥ 2♣.", "Du checkst.", "Der Button setzt 1,8bb (1/3 Pot)."],
        hand: "Kein Paar, aber vier Herz: ein Flush-Draw. 9 Herz sind noch im Deck (9 Outs). Dazu kann ein König dir ein Paar geben.",
        prompt: "Der Button setzt 1,8bb in einen Pot von 5,5bb. Was tust du?",
        options: ["Passen", "Mitgehen (1,8bb)", "Check-Raise auf 6bb"],
        answer: 1,
        ok: [2],
        why: "Pot Odds: Du zahlst 1,8bb, um am Ende 5,5 + 1,8 + 1,8 = 9,1bb zu gewinnen. Du brauchst also 1,8 ÷ 9,1 ≈ 20 % Equity. Mit 9 Outs und zwei kommenden Karten hast du nach der 4er-Regel etwa 9 × 4 = 36 %. Klarer Call. (Ein Check-Raise als Semi-Bluff ist auch eine gute Option.)",
        next: "Pot: 5,5 + 1,8 + 1,8 = 9,1bb.",
      },
      {
        street: "turn", board: ["Jh", "6h", "2c", "3s"], pot: 9.1,
        log: ["Der Turn ist die 3♠. Kein Herz.", "Du checkst.", "Der Button setzt 3bb (1/3 Pot)."],
        hand: "Immer noch ein Flush-Draw. Jetzt kommt nur noch eine Karte (der River).",
        prompt: "Der Button setzt 3bb in einen Pot von 9,1bb. Was tust du?",
        options: ["Passen", "Mitgehen (3bb)", "All-in"],
        answer: 1,
        why: "Du brauchst 3 ÷ (9,1 + 3 + 3) ≈ 20 % Equity. Mit nur noch einer Karte gilt die 2er-Regel: 9 Herz-Outs × 2 ≈ 18 %, dazu manchmal ein König (3 weitere Outs, ≈ 6 %). Zusammen etwa 24 %, also reicht es knapp für einen Call. Gegen eine große Bet wäre Passen richtig.",
        next: "Pot: 9,1 + 3 + 3 = 15,1bb.",
      },
      {
        street: "river", board: ["Jh", "6h", "2c", "3s", "8d"], pot: 15.1,
        log: ["Der River ist die 8♦. Dein Flush ist nicht angekommen.", "Du checkst.", "Der Button setzt 11bb (ca. 3/4 Pot)."],
        hand: "Nur König-hoch. Du schlägst nur Bluffs mit noch schwächeren Karten.",
        prompt: "Der Button setzt 11bb in einen Pot von 15,1bb. Was tust du?",
        options: ["Passen", "Mitgehen (11bb)", "All-in"],
        answer: 0,
        why: "Du bräuchtest 11 ÷ (15,1 + 22) ≈ 30 % Gewinnchance, aber mit König-hoch gewinnst du so gut wie nie. Und die MDF? Sie sagt, dass du mit etwa 58 % der Hände weiterspielen musst, die du jetzt noch hältst. Dafür nimmst du deine besten Hände (Buben, Sechsen, Paare). Die schwächsten Hände deiner Range, wie dieser verpasste Draw, passen.",
        next: "Du passt. Der Button gewinnt den Pot. Verpasste Draws zu folden ist normal und kein Fehler.",
      },
    ],
  },
  {
    id: "fold-ajo",
    title: "AJo gegen eine UTG-Eröffnung",
    teaser: "Eine Hand, die gut aussieht, aber gegen eine frühe Eröffnung gepasst wird.",
    lesson: "Spiel gegen eine Eröffnung, dominierte Hände",
    players: 6, hero: "CO", villain: "UTG", heroCards: ["Ad", "Jc"],
    steps: [
      {
        street: "preflop", board: [], pot: 4,
        notes: { UTG: "Erhöht 2,5bb", BTN: "Noch dran", SB: "Noch dran", BB: "Noch dran" },
        log: ["UTG erhöht auf 2,5bb.", "HJ passt."],
        hand: "A♦J♣: Ass-Bube offsuit. Sieht stark aus.",
        prompt: "UTG, der erste Spieler, hat erhöht. Du sitzt im Cutoff, nach dir kommen noch Button und Blinds. Was tust du?",
        options: ["Passen", "Mitgehen (2,5bb)", "3-Bet auf 7,5bb"],
        answer: 0,
        why: "UTG eröffnet nur etwa 19 % der Hände, darunter AQ, AK und viele hohe Paare. Gegen diese Range ist AJo oft dominiert: Triffst du ein Ass, hat UTG häufig ein Ass mit besserem Kicker. Dazu können Button und Blinds noch squeezen. Gegen eine späte Eröffnung wäre AJo dagegen eine starke Hand.",
        next: "Du passt. Probier im Ranges-Tab „Gegen eine Eröffnung“ aus, wie sich das ändert, wenn der Button statt UTG eröffnet.",
      },
    ],
  },
  {
    id: "3bet-bluff",
    title: "3-Bet-Bluff mit A♠5♠ aus dem Small Blind",
    teaser: "Warum man mit einer kleinen Ass-Hand re-raist und wie es nach dem Flop weitergeht.",
    lesson: "3-Bet, Blocker, C-Bet als Semi-Bluff",
    players: 6, hero: "SB", villain: "CO", heroCards: ["As", "5s"],
    steps: [
      {
        street: "preflop", board: [], pot: 4,
        notes: { CO: "Erhöht 2,5bb", BB: "Noch dran" },
        log: ["UTG und HJ passen.", "Der Cutoff erhöht auf 2,5bb.", "Der Button passt."],
        hand: "A♠5♠: ein Ass mit kleiner Karte, suited.",
        prompt: "Der Cutoff hat erhöht. Du sitzt im Small Blind (0,5bb investiert). Was tust du?",
        options: ["Passen", "Mitgehen (2bb mehr)", "3-Bet auf 11bb"],
        answer: 2,
        why: "Aus dem Small Blind spielt man meist 3-Bet oder Passen, weil Mitgehen ohne Position mit dem BB im Rücken Geld kostet. A5s ist ein klassischer 3-Bet-Bluff: Das Ass ist ein Blocker (der Cutoff hat seltener AA oder AK), und wenn er mitgeht, kannst du immer noch den Nut-Flush oder eine Wheel-Straße machen.",
        next: "Der BB passt, der Cutoff geht mit. Pot: 11 + 11 + 1 (BB) = 23bb.",
      },
      {
        street: "flop", board: ["Ks", "8s", "3h"], pot: 23,
        log: ["Der Flop kommt: K♠ 8♠ 3♥.", "Du bist zuerst dran."],
        hand: "Kein Paar, aber vier Pik inklusive Ass: ein Nut-Flush-Draw (9 Outs zur bestmöglichen Hand).",
        prompt: "Du hast preflop die 3-Bet gemacht und handelst zuerst. Was tust du?",
        options: ["Checken", "C-Bet klein: 8bb (ca. 1/3 Pot)", "All-in: 89bb"],
        answer: 1,
        ok: [0],
        why: "Auf einem Board mit König hat der 3-Bettor den Range-Vorteil: Du kannst KK, AK und AA haben, der Cutoff hätte diese Hände oft selbst 4-gebettet. Eine kleine C-Bet setzt ihn unter Druck. Mit deinem Draw ist das ein Semi-Bluff: Wenn er mitgeht, kannst du trotzdem noch den Nut-Flush treffen. (Checken ist auch vertretbar.)",
        next: "Der Cutoff passt. Du gewinnst 23bb, ohne eine fertige Hand zu haben.",
      },
    ],
  },
  {
    id: "wet-board",
    title: "Nasses Board: Wann man nicht c-bettet",
    teaser: "Du eröffnest A♣K♣ aus UTG, aber der Flop passt viel besser zum Gegner.",
    lesson: "Board-Textur, Range-Vorteil, Pot Odds",
    players: 6, hero: "UTG", villain: "BB", heroCards: ["Ac", "Kc"],
    steps: [
      {
        street: "preflop", board: [], pot: 1.5,
        notes: { HJ: "Noch dran", CO: "Noch dran", BTN: "Noch dran", SB: "Noch dran", BB: "Noch dran" },
        log: ["Du bist der erste Spieler, der handelt."],
        hand: "A♣K♣: Ass-König suited, eine Premium-Hand.",
        prompt: "Du sitzt UTG, alle fünf anderen Spieler handeln nach dir. Was tust du?",
        options: ["Passen", "Mitgehen (Limpen, 1bb)", "Erhöhen auf 2,5bb"],
        answer: 2,
        why: "AKs ist eine der stärksten Hände und wird von jedem Platz eröffnet, auch aus der frühesten Position.",
        next: "Alle passen bis zum BB, der mitgeht. Pot: 5,5bb.",
      },
      {
        street: "flop", board: ["8h", "7h", "6c"], pot: 5.5,
        log: ["Der Flop kommt: 8♥ 7♥ 6♣.", "Der BB checkt."],
        hand: "Nur Ass-hoch, kein Paar und kein Draw (keine Herz, keine Straßen-Chance).",
        prompt: "Der BB checkt zu dir. Was tust du?",
        options: ["Checken", "Klein setzen: 1,8bb", "Groß setzen: 4bb"],
        answer: 0,
        why: "8-7-6 mit zwei Herz ist ein sehr nasses, niedriges Board. Es trifft die breite Range des BB (98, 54, 65, T9, kleine Paare mit Set) viel besser als deine UTG-Range mit vielen hohen Karten. Hier verlierst du den Range-Vorteil. Mit einer Hand ohne Paar und ohne Draw checkst du.",
        next: "Du checkst. Pot bleibt bei 5,5bb.",
      },
      {
        street: "turn", board: ["8h", "7h", "6c", "2s"], pot: 5.5,
        log: ["Der Turn ist die 2♠.", "Der BB setzt 3,7bb (2/3 Pot)."],
        hand: "Immer noch nur Ass-hoch. Ein Ass oder König am River gäbe dir ein Paar (6 Outs).",
        prompt: "Der BB setzt 3,7bb in einen Pot von 5,5bb. Was tust du?",
        options: ["Passen", "Mitgehen (3,7bb)", "Erhöhen auf 12bb"],
        answer: 0,
        why: "Du brauchst 3,7 ÷ (5,5 + 3,7 + 3,7) ≈ 29 % Equity. Mit einer kommenden Karte und 6 Outs hast du etwa 6 × 2 = 12 %, und selbst ein Paar Asse ist auf diesem Board oft nicht vorne. Viel zu wenig: Passen. Auch starke Starthände muss man loslassen, wenn das Board nicht passt.",
        next: "Du passt. Du verlierst nur deine 2,5bb vom Preflop.",
      },
    ],
  },
  {
    id: "river-bluff",
    title: "Semi-Bluff und River-Bluff mit Q♠J♠",
    teaser: "Ein starker Draw, der nicht ankommt, und warum du am River trotzdem setzt.",
    lesson: "Semi-Bluff, Bluff-Anteil, Showdown-Value",
    players: 6, hero: "BTN", villain: "BB", heroCards: ["Qs", "Js"],
    steps: [
      {
        street: "preflop", board: [], pot: 1.5,
        notes: { SB: "Noch dran", BB: "Noch dran" },
        log: ["UTG, HJ und CO passen."],
        hand: "Q♠J♠: Dame-Bube suited, eine gut spielbare Hand.",
        prompt: "Alle haben bis zu dir gepasst. Was tust du?",
        options: ["Passen", "Mitgehen (Limpen, 1bb)", "Erhöhen auf 2,5bb"],
        answer: 2,
        why: "QJs ist am Button eine klare Eröffnung: zwei Broadway-Karten, suited, und du hast nach dem Flop Position.",
        next: "Der SB passt, der BB geht mit. Pot: 5,5bb.",
      },
      {
        street: "flop", board: ["Ts", "9d", "3s"], pot: 5.5,
        log: ["Der Flop kommt: T♠ 9♦ 3♠.", "Der BB checkt."],
        hand: "Kein Paar, aber ein riesiger Draw: Flush-Draw (9 Pik) plus Open-Ended Straight Draw (jeder König oder jede Acht). Zusammen etwa 15 Outs.",
        prompt: "Der BB checkt zu dir. Was tust du?",
        options: ["Checken", "Setzen: 3,5bb (ca. 2/3 Pot)", "All-in: 97,5bb"],
        answer: 1,
        why: "Das ist ein Semi-Bluff: Du kannst den Gegner sofort zum Passen bringen, und wenn er mitgeht, hast du mit 15 Outs trotzdem über 50 % Equity. All-in wäre zu groß, weil nur noch bessere Hände mitgehen.",
        next: "Der BB geht mit. Pot: 5,5 + 3,5 + 3,5 = 12,5bb.",
      },
      {
        street: "turn", board: ["Ts", "9d", "3s", "4h"], pot: 12.5,
        log: ["Der Turn ist die 4♥. Nichts getroffen.", "Der BB checkt."],
        hand: "Immer noch Flush-Draw plus Straight-Draw, eine Karte kommt noch.",
        prompt: "Der BB checkt wieder. Was tust du?",
        options: ["Checken", "Setzen: 8bb (ca. 2/3 Pot)", "All-in: 94bb"],
        answer: 1,
        ok: [0],
        why: "Weiter Druck machen: Der BB passt mit vielen Händen, und wenn nicht, hast du noch etwa 30 % (15 Outs × 2). Checken ist auch vertretbar, dann siehst du den River kostenlos.",
        next: "Der BB geht wieder mit. Pot: 12,5 + 8 + 8 = 28,5bb.",
      },
      {
        street: "river", board: ["Ts", "9d", "3s", "4h", "2c"], pot: 28.5,
        log: ["Der River ist die 2♣. Dein Draw ist nicht angekommen.", "Der BB checkt."],
        hand: "Nur Dame-hoch. Beim Showdown verlierst du gegen fast jede Hand, die so lange mitgegangen ist.",
        prompt: "Der BB checkt. Was tust du?",
        options: ["Checken (Showdown)", "Bluffen: 21bb (ca. 3/4 Pot)", "Passen"],
        answer: 1,
        why: "Checken heißt hier fast sicher verlieren: Dame-hoch hat keinen Showdown-Value. Ein Bluff ist die einzige Chance, den Pot zu gewinnen. Bei einer 3/4-Pot-Bet sollten etwa 21 ÷ (28,5 + 42) ≈ 30 % deiner Bets Bluffs sein. Verpasste Draws sind dafür die idealen Kandidaten. (Passen geht nicht, niemand hat gesetzt.)",
        next: "Der BB denkt lange nach und passt. Du gewinnst 28,5bb mit Dame-hoch.",
      },
    ],
  },
];
